[package]
name = "embedded-graphics"
description = "Embedded graphics library for small hardware displays"
version = "0.4.9-alpha.0"
authors = ["James Waples <james@wapl.es>"]
repository = "https://github.com/jamwaffles/embedded-graphics"
documentation = "https://docs.rs/embedded-graphics"
categories = ["embedded", "no-std"]
keywords = ["rtfm", "graphics", "embedded"]
readme = "../README.md"
license = "MIT OR Apache-2.0"
exclude = [
	".travis.yml",
	".gitignore",
	"convert_1bpp.sh",
]
edition = "2018"

[badges]
travis-ci = { repository = "jamwaffles/embedded-graphics", branch = "master" }

[dependencies]
nalgebra = { version = "0.16.0", optional = true, default-features = false }
tinybmp = "0.1.0"

[features]
default = []
nalgebra_support = [ "nalgebra" ]
