[package]
name = "embedded-graphics"
description = "Embedded graphics library for small hardware displays"
version = "0.2.0"
authors = ["James Waples <jamwaffles@gmail.com>"]
repository = "https://github.com/jamwaffles/embedded-graphics"
documentation = "https://docs.rs/embedded-graphics"
categories = ["embedded", "no-std"]
keywords = ["rtfm", "graphics", "embedded"]
readme = "../README.md"
license = "MIT OR Apache-2.0"
exclude = [
	".travis.yml",
	".gitignore",
	"convert_1bpp.sh",
]

[badges]
travis-ci = { repository = "jamwaffles/embedded-graphics", branch = "master" }

[dependencies]
nalgebra = { version = "0.16.0", optional = true, default-features = false }

[features]
default = []
nalgebra_support = [ "nalgebra" ]
